// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJo-_iNupzUDm2fvDP4vwn_mUu-w9AXT0',
    appId: '1:479856845671:web:8627c6449727084bd005c2',
    messagingSenderId: '479856845671',
    projectId: 'api-app-cb3ff',
    authDomain: 'api-app-cb3ff.firebaseapp.com',
    storageBucket: 'api-app-cb3ff.firebasestorage.app',
    measurementId: 'G-0W6ECP3HWN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAanGB3xHFuc9H145x9sNm5zZYa2rqwYjM',
    appId: '1:479856845671:ios:8324fd5954da171bd005c2',
    messagingSenderId: '479856845671',
    projectId: 'api-app-cb3ff',
    storageBucket: 'api-app-cb3ff.firebasestorage.app',
    iosBundleId: 'com.example.apiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAanGB3xHFuc9H145x9sNm5zZYa2rqwYjM',
    appId: '1:479856845671:ios:8324fd5954da171bd005c2',
    messagingSenderId: '479856845671',
    projectId: 'api-app-cb3ff',
    storageBucket: 'api-app-cb3ff.firebasestorage.app',
    iosBundleId: 'com.example.apiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJo-_iNupzUDm2fvDP4vwn_mUu-w9AXT0',
    appId: '1:479856845671:web:f7b5f00140ab0526d005c2',
    messagingSenderId: '479856845671',
    projectId: 'api-app-cb3ff',
    authDomain: 'api-app-cb3ff.firebaseapp.com',
    storageBucket: 'api-app-cb3ff.firebasestorage.app',
    measurementId: 'G-B2S2LR20BJ',
  );
}
